# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: false

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
  - mserizawa
  - AtsushiM
  - meganemura
  - t-mori23
  - marumarism
  - f440
  - motsat
  - tkimi
  - wakasa51
  - wata727
  - kouryou


# A list of keywords to be skipped the process that add reviewers if pull requests include it
skipKeywords:

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 2
